### ISSUE TITLE
Slider not working

### ISSUE THREAD

**Issue by Narumiii** [aXenDeveloper/ips-theme-dynamic#1]
Hi, thank you for the theme it looks nice, the only problem i have found is the slider dones't work even when is enabled.

My IPS Version is 4.6 BETA 2

here are some screenshots.

![Screenshot_1](https://user-images.githubusercontent.com/37037181/120858953-d3d0db80-c583-11eb-9283-8eb8dbbb5d37.png)
![Screenshot_2](https://user-images.githubusercontent.com/37037181/120858958-d4697200-c583-11eb-9b10-94ac7683c77c.png)

**Comment by aXenDeveloper** [comment]
Change "Display slider by URL" settings.

**Comment by Narumiii** [comment]
Done working, thank you.
