### ISSUE TITLE
Konfiguracja nagłówka/stopki

### ISSUE THREAD

**Issue by Misiek79** [aXenDeveloper/ips-theme-dynamic#12]
Jak poprawnie skonfigurować nagłówek i stopkę?  Jeśli można jakiś przykład podać. Z góry dziękuję

![1](https://user-images.githubusercontent.com/118826165/203634646-b1f7d50b-333b-4e08-8ea2-59efbb92bae4.jpg)

IPS 4.7.4
PHP 8.1
Dynamic Theme 1.3

**Comment by aXenDeveloper** [comment]
Zależy co tam chcesz mieć.

**Comment by Misiek79** [comment]
Np. możliwość załadowania jakiegoś pliku zdjęciowego np. jpg lub tekast

**Comment by aXenDeveloper** [comment]
Na screenie jest to jedna z opcji motywów w IPS. Obsługuje kod HTML. Zerknij na to:
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img
