### ISSUE TITLE
For some reason slider images don't load in, I tried with mulitple images

### ISSUE THREAD

**Issue by MeapVR** [aXenDeveloper/ips-theme-dynamic#2]
Whenever I set a slider image the images don't load in.

**Comment by aXenDeveloper** [comment]
Show me your settings.

**Comment by MeapVR** [comment]
Here are my settings:
Awesome theme by the way! I love it.

![image](https://user-images.githubusercontent.com/32072093/123551002-2e6aeb00-d770-11eb-8216-1d2a8edb21fb.png)
![image](https://user-images.githubusercontent.com/32072093/123551006-34f96280-d770-11eb-8da4-c10ee5b12472.png)

**Comment by aXenDeveloper** [comment]
``Display slider by URL`` settings is invalid for your website.

**Comment by MeapVR** [comment]
![image](https://user-images.githubusercontent.com/32072093/123551719-4132ef00-d773-11eb-99d7-1f04c964efb6.png)
I just changed it to this but it still seems to not be working. Do you know what I am doing wrong?

**Comment by MeapVR** [comment]
I removed the / and now this happens
![image](https://user-images.githubusercontent.com/32072093/123551769-72abba80-d773-11eb-9a9f-cf04366ed4a7.png)

**Comment by aXenDeveloper** [comment]
Replace ``localhost`` to your URL website.

**Comment by MeapVR** [comment]
It still does not work I replaced localhost with my domain name.

**Comment by aXenDeveloper** [comment]
I find bug. Please change ``Where to display the slider?`` settings to ``Everywhere``.

**Comment by aXenDeveloper** [comment]
Or download new version theme :)

**Comment by MeapVR** [comment]
Changing it to everywhere did not work either for me and on the marketplace page is does not say a new version is available :(

**Comment by aXenDeveloper** [comment]
Write to me in a private message via the IPS marketplace and provide me with the AdminCP data with the permission to the theme.
I'll take a look at what's wrong.

**Comment by MeapVR** [comment]
Should I just delete and redownload the theme from the marketplace?

**Comment by MeapVR** [comment]
Deleting the theme and downloading it again from the marketplace worked. Thank you for your help. Keep up the amazing work! :)
