### ISSUE TITLE
Unchangeable black text

### ISSUE THREAD

**Issue by SpamSPez** [aXenDeveloper/ips-theme-dynamic#3]
I have noticed in the checkout screen when entering card details, the text for the card number, CVS, and the expiration date is black.
There doesn't seem to be an option to change the text color. I have attached an Imgur photo below.

[https://i.imgur.com/3nOHYf0.png](url)

**Comment by aXenDeveloper** [comment]
Sorry for the delay. I'll investigate this weekend.

**Comment by SpamSPez** [comment]
> Sorry for the delay. I'll investigate this weekend.

Thank you for getting around to the issue. I looked into it myself, and it seems the text color is controlled by Stripe.js. Of course, I could be wrong, but who knows. Fortunately, invision does allow themes to change the background color of the boxes, so maybe that could work as a solution?

**Comment by aXenDeveloper** [comment]
Yes, I implemented changing the background to white so that the inscription is visible only in forms from stripe.
I can't change text color.

![image](https://user-images.githubusercontent.com/58148176/157908411-15fe704a-43b3-4a3e-bb78-a0f42f875e2d.png)
