### ISSUE TITLE
Support Replies Information Box

### ISSUE THREAD

**Issue by Pyon1234** [aXenDeveloper/ips-theme-dynamic#8]
Possible to change the background as the text is hard to read and it doesn't fit in with the rest of the theme? Thanks
https://gyazo.com/8724e5fd1ad2f2c6b34f44099946d0a3
Or at least tell me how to do it myself.
Other then that, the best theme for free out there!

**Comment by aXenDeveloper** [comment]
Is this a Commerce application?

**Comment by Pyon1234** [comment]
> 

Yes it is

**Comment by aXenDeveloper** [comment]
I see. You can change this background by add this code into custom.css.

```
.cNexusSupportMessage_m .cNexusSupportMessage_author, .cNexusSupportMessage_a .cNexusSupportMessage_author {
    background: rgb( var(--theme-area_background) );
}
```
